<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "blsvfragebogen"
 *
 * Auto generated by Extension Builder 2013-08-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Fragebogen',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Berti Golf,, Martin Gonschor',
	'author_email' => 'berti.golf@blsv.de, martin.gonschor@blsv.de',
	'author_company' => 'BLSV, BLSV',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => 'templates,partials',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>